name: extract_partition

on:
  workflow_dispatch:
    inputs:
      rom_url:
        description: 'ROM 下载直链'
        required: true
        default: 'https://bkt-sgp-miui-ota-update-alisgp.oss-ap-southeast-1.aliyuncs.com/OS1.0.2.0.UKMCNXM/miui_ODIN_OS1.0.2.0.UKMCNXM_af3b0d3530_14.0.zip'
      boot:
        description: 'boot'
        required: false
        default: true
        type: boolean
      init_boot:
        description: 'init_boot'
        required: false
        default: true
        type: boolean
      dtbo:
        description: 'dtbo'
        required: false
        default: false
        type: boolean
      vendor:
        description: 'vendor'
        required: false
        default: false
        type: boolean
      imgs:
        description: '自定义提取镜像, 使用半角","分割'
        required: false
        default: ""

jobs:
  extract_partition:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4.1.4
      
      - name: 安装依赖
        run: |
          sudo apt-get update
          sudo apt-get -y install python3 python3-pip
          sudo pip3 install bsdiff4 enlighten protobuf==3.20 httpx
          git clone --single-branch --depth=1 https://github.com/5ec1cff/payload-dumper/tree/master/src/payload_dumper ~/payload-dumper_temp
          mv ~/payload-dumper_temp/payload_dumper ~/payload-dumper
          rm -rf ~/payload-dumper_temp
          BUILD_TIME=$(TZ=Asia/Shanghai date +"%Y%m%d%H%M")
          echo "BUILD_TIME=$BUILD_TIME" >> $GITHUB_ENV
      - name: 提取镜像
        run: |
          partitions=""
          add_partition() {
            if [ "$1" == "true" ]; then
              partitions="$partitions,$2"
            fi
          }
          if [ "${{ github.event.inputs.imgs }}" != "" ]; then
            partitions="$partitions,${{ github.event.inputs.imgs }}"
          fi
          add_partition "${{ github.event.inputs.boot }}" "boot"
          add_partition "${{ github.event.inputs.init_boot }}" "init_boot"
          add_partition "${{ github.event.inputs.dtbo }}" "dtbo"
          add_partition "${{ github.event.inputs.vendor }}" "vendor"
          if [ -z "$partitions" ]; then
            echo "请选择至少一个分区类型！"
            exit 1
          fi
          cd ~ && python3 ~/payload-dumper/dumper.py --partitions "${partitions:1}" ${{ github.event.inputs.rom_url }}

      - name: 生成信息文件
        run: |
          cd ~/output
          echo "提交日期：$(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S')" >> ${{ github.workspace }}/info.md
          echo "ROM 下载直链：${{ github.event.inputs.rom_url }}" >> ${{ github.workspace }}/info.md
          echo "提取的镜像大小：" >> ${{ github.workspace }}/info.md
          for img_file in *.img; do
            echo "$(du -h "$img_file" | awk '{print $1}') $img_file" >> ${{ github.workspace }}/info.md
          done

      - name: 压缩镜像文件
        run: |
          cd ~/output
          for img_file in *.img; do
            echo "正在打包压缩: $img_file"
            tar -zcvf "$img_file.tar.gz" "$img_file"
            echo "        >>$img_file.tar.gz"
          done

      - name: 上传镜像及相关信息
        uses: ncipollo/release-action@v1.14.0
        with:
            artifacts: "~/output/*"
            bodyfile: "${{ github.workspace }}/info.md"
            tag: "OUTPUT_${{ env.BUILD_TIME }}_${{ github.run_id }}"
            token: ${{ secrets.GITHUB_TOKEN }}
