name: Delete old releases tags

on:
  workflow_dispatch:
    # schedule:
    #   - cron: '0 0 * * *' # Uncomment to run daily at midnight

jobs:
  delete_old_releases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest release tag
        id: get_latest_release
        uses: actions/github-script@v7
        with:
          script: |
            const { data: tags } = await github.rest.repos.listTags({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            // Assuming the latest tag is the first one alphabetically
            const latestTag = tags[0].name;
            console.log(`Latest release tag: ${latestTag}`);
            return latestTag;

      - name: Delete old releases
        if: steps.get_latest_release.outputs.result != ''
        env:
          GITHUB_TOKEN: ${{ secrets.TOKENS }}
        run: |
          git fetch --tags
          # Assuming you want to keep the latest 1 tags for example
          git tag --sort=-creatordate | head -n -1 | xargs -d '\n' git tag -d